### ISSUE TITLE
Use the IAM role attached worker node EC2 instance profile rather than pass in aws creds to the application

### ISSUE THREAD

**Issue by agconti** [practo/k8s-worker-pod-autoscaler#103]
Is this possible with the current version of WPA?

This is [a feature](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#id3) that other tools like boto provide that's really valuable. It would make credentials management more streamlined for the autoscaler.  Is it possible with the libraries you're using for WPA?

Thanks for publishing this project. I loved your blog post and think this tool is super cool! 💖

**Comment by alok87** [comment]
Happy to hear you find it useful. :)

Yes, the sqs library in go also behave in the same way as boto. It will work. I just checked in the staging environment we are running it without env variables and the WPA pods assumes the role of the node in which the WPA pod is running.

If you are using something like [kiam](https://github.com/uswitch/kiam) then it may require few more changes.

I will update the document to clear out this confusion, thanks for raising it.

**Comment by agconti** [comment]
Awesome, Thank you!

**Comment by agconti** [comment]
Confrimed
