### ISSUE TITLE
No v.1.1.0 docker image?

### ISSUE THREAD

**Issue by mf-lit** [practo/k8s-worker-pod-autoscaler#107]
Looks like the v1.1.0 release has gone out, I'm excited to test it. But it seems there's no 1.1.0 docker image in dockerhub?

Probably I'm being too impatient since the release was only a few hours ago. But just thought I'd check in case it was an oversight...

**Comment by alok87** [comment]
@mf-lit Forgot to push the image after taking the pull. Pushed the following images, please try out and give feedback. :)

```
pushed: practodev/workerpodautoscaler:v1.1.0-1-g1ce554b
pushed: practodev/workerpodautoscaler:v1.1
pushed: practodev/workerpodautoscaler:v1
```

**Comment by alok87** [comment]
Please reopen if needed, closing this.
