### ISSUE TITLE
Deployment gets stuck MinimumReplicasUnavailable

### ISSUE THREAD

**Issue by mihaivinaga** [practo/k8s-worker-pod-autoscaler#117]
I have upgraded to the last library and since then I am having issues with the autoscaler. What happens is this after a period of time the pod that does the scaling gets stuck in pending. This is the error that I am getting:

`Get "https://10.70.152.3:10250/containerLogs/kube-system/workerpodautoscaler-f898df7cb-wdsb7/wpa?tailLines=5000×tamps=true": dial tcp 10.70.152.3:10250: connect: no route to host
`

When I check the autoscaler deployment I get another message:

```
MinimumReplicasUnavailable
Deployment does not have minimum availability
```

This started happening after I've upgraded to the last version. It cannot be a problem of availability because I have 50+ nodes in kubernetes cluster. The only way that I get it to work is if I delete the cluster and recreate it from scratch.

Any pointers on what might be causing this?

**Comment by alok87** [comment]
First [search result on no route to host](https://stackoverflow.com/questions/58268197/kubernetes-dial-tcp-myip10250-connect-no-route-to-host). 
```
This error indicates that the Kubernetes API server is unable to reach the node. This has nothing to do with your containers, pods or even your CNI network. no route to host indicates that either:

The host is unavailable
A network segmentation has occurred
The Kubelet is unable to answer the API server
```
Looks like an k8s environment issue..

These environment related information can help me help you:

- Kubernetes environment, version you are using.
- WPA version? are you are v1.1.0? Did you follow [this](https://github.com/practo/k8s-worker-pod-autoscaler/blob/master/UPGRADE.md), 
- Output of `kubectl get deployment workerpodautoscaler -o yaml -n kube-system`
- Is your deployment.yaml same as [this](https://github.com/practo/k8s-worker-pod-autoscaler/blob/master/artifacts/deployment-template.yaml) ?
- Is your CRD same as [this](https://github.com/practo/k8s-worker-pod-autoscaler/blob/master/artifacts/crd.yaml) ?
- Can you share the Kubernetes Deployment resource and WPA resource (if possible)?
```
kubectl get deploy <ur_deploy_name> -n <namespace> -o yaml
kubectl get wpa <ur_wpa_name> -n <namespace> -o yaml
```
