### ISSUE TITLE
Question: Gracefull shutdown?

### ISSUE THREAD

**Issue by koenverwimp** [practo/k8s-worker-pod-autoscaler#121]
How can I be sure that pods are not killed in the middle of processing a SQS message during downscaling?

**Comment by alok87** [comment]
For workers which cannot tolerate or want to tolerate disruptions due to scale down and want only to scale down when nothing is being processed. You can set maxDisruption=0%. This will shutdown all workers when nothing is being processed.

**Comment by alok87** [comment]
Please reopen this if required.
