### ISSUE TITLE
Scale based on: `numMessages +1`

### ISSUE THREAD

**Issue by agconti** [practo/k8s-worker-pod-autoscaler#127]
### Question 
Is there a way to set `targetMessagesPerWorker` so that it scales based on the number of messages in the queue +1?

#### Background
I currently have `targetMessagesPerWorker` set to 1 so that it scales a new pod for each message.  Each pod lives on its own node so scale-up can take a long time to add the new node to the cluster.  To reduce the time it takes to start processing a message, I'd like to have an extra node always available. That way it can start processing as soon as the message is added to the queue.  

Is there a way that I can scale the HPA based on the formula: `messageCount + 1`?

####  Failed workarounds
- Set `targetMessagesPerWorker` to a fraction (0.5). This would ensure that there are always more replicas than messages, which would keep startup times low. However, there will be some instances scaled needlessly. ie. if targetMessagesPerWorker: 0.5 -> 1 message in queue = 2 nodes (perfect!), but 5 message in queue = 10 nodes (5 nodes wasted!).
- Set `minReplicas` to 1. This ensures that there is always a replica ready to use when the queue is 0. However, it won't decrease start times for workloads requiring more than 1 message.

**Comment by alok87** [comment]
> To reduce the time it takes to start processing a message, I'd like to have an extra node always available.

You can use the [Over-provisioning feature](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler) of [Kubernetes Cluster Autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) to solve this problem.

**Comment by agconti** [comment]
Thanks @alok87! I didn't know about this feature. I appreciate your help.
