### ISSUE TITLE
The manifest for public.ecr.aws/practo/workerpodautoscaler:v1.6.0 is not found on the public ECR

### ISSUE THREAD

**Issue by vaskozl** [practo/k8s-worker-pod-autoscaler#146]
I can pull v1.5.0 out of ECR fine, but not v1.6.0.

The changelog suggest that it has been pushed to ECR.

```
~  > docker pull 'public.ecr.aws/practo/workerpodautoscaler:v1.6.0'
Error response from daemon: manifest for public.ecr.aws/practo/workerpodautoscaler:v1.6.0 not found: manifest unknown: Requested image not found
````

**Comment by alok87** [comment]
Yes it was missed to be pushed. I will fix this, you can use `practodev` meanwhile.

**Comment by alok87** [comment]
@justjkk please help with this.

**Comment by justjkk** [comment]
Pushed the [v1.6.0](docker pull 'public.ecr.aws/practo/workerpodautoscaler:v1.6.0') image to public ecr and also fixed the credential helper configuration so that it happens automatically going forward.
