### ISSUE TITLE
[SQS] Prevent DLQ issue when bootup time is more

### ISSUE THREAD

**Issue by alok87** [practo/k8s-worker-pod-autoscaler#29]
Prevent DLQ issue in aws sqs when bootup time is more

cc @anuragagarwal561994

**Comment by anuragagarwal561994** [comment]
Instead of long polling can we try using some trigger for SQS job insert in the queue. This can prevent DLQ and keep the api calls to minimum.

**Comment by alok87** [comment]
Closes with #31
