### ISSUE TITLE
Scale down can happen when worker deletes the job before processing 

### ISSUE THREAD

**Issue by anuragagarwal561994** [practo/k8s-worker-pod-autoscaler#30]
When a job is there in SQS, a worker picks that job, then deletes that job and then starts the processing. And say takes 5 minutes to process the job. And on success does nothing and on failure re inserts the job.

WPA would scale down this worker.
How do you propose to fix this issue with SQS ?

**Comment by alok87** [comment]
Yes but deleting the job then doing the processing is a bad design. Job should be deleted after the processing is done.

**Comment by anuragagarwal561994** [comment]
It depends on whether it a good / bad design based on use case we are trying to tackle, can you have an article to support your statement.

Arguments in support where this can be useful is when there are long running jobs and you don't want the job to be cancelled and repeated again once the timeout expires, one wants to take control at application level of how a job should be scheduled next if it fails once.

**Comment by alok87** [comment]
This use is not supported at present.

**Comment by alok87** [comment]
Closing this as this behaviour is not compatible with any scaling logic.
