### ISSUE TITLE
Handle SQS NonExistentQueue error

### ISSUE THREAD

**Issue by justjkk** [practo/k8s-worker-pod-autoscaler#33]
WPA pod goes into crash loop when atleast one of the queues it is monitoring is not present or deleted.

```
F0918 13:33:13.220319       1 sqs.go:273] Unable to get approximate messages in queue "sample-queue", AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
```

I think the best option here is to skip scaling instead of crashing so that when the queue gets created later on(when a producer is actually trying to send message), wpa can resume scaling.

**Comment by alok87** [comment]
Agree. Also we need to log a kubernetes event for WPA object saying "queue not found"

**Comment by alok87** [comment]
cc @adityabhatia02

**Comment by alok87** [comment]
https://github.com/practo/k8s-worker-pod-autoscaler/blob/master/pkg/controller/controller.go#L325-L326

logging event ^

**Comment by justjkk** [comment]
Found that this issue is already handled when [long polling](https://github.com/practo/k8s-worker-pod-autoscaler/blob/68c8f3d48d583675f3a05e0df83ed97d8107b5da/pkg/queue/sqs.go#L255)
