### ISSUE TITLE
Update AWS version to support IAM for Service Accounts

### ISSUE THREAD

**Issue by badbeeker** [practo/k8s-worker-pod-autoscaler#49]
Any chance this could support a aws sdk version that allows IAM for Service Accounts instead of passing the secrets as environment variables?

Would this be as easy as updating the go aws sdk to a version past 1.23.13?  Perhaps the latest 1.28.12?

Related https://github.com/practo/k8s-worker-pod-autoscaler/issues/51

**Comment by alok87** [comment]
Closed with #55
