### ISSUE TITLE
Only massive scale down is possible with WPA at present (WPA only supports scale down to min)

### ISSUE THREAD

**Issue by alok87** [practo/k8s-worker-pod-autoscaler#50]
Say, for example: 
You have the following WPA configuration
```
min = 0
max = 20
target = 10
```

- Say, we got 100 messages in the queue then WPA scales up the number of pods.  Good 👍 
- But, WPA scales down all the pods from the current number to min(0) only when there are no messages in the queue and **none of the workers are doing the processing(emptyReceives)**

WPA at present does not know the workers which are idle and which are still processing. It only knows if all are not processing or not. Therefore it does not assume the workers to be idempotent and waits for all workers to finish processing then it scales down all together to the min.

**Problem**
Massive scale down is not cost efficient. We can discuss and find ways to solve this.

cc @anujith-singh @jotish

**Comment by caiohasouza** [comment]
Hello,

Yes, yesterday i found this out in my tests.
