### ISSUE TITLE
Following the install guide, `hack/install.sh` attempts to deploy a non-existent tag

### ISSUE THREAD

**Issue by ryantate13** [practo/k8s-worker-pod-autoscaler#82]
The leads to an `ImagePullBackoff` scenario for `practodev/workerpodautoscaler:v1.0.0-beta`. Would be nice if we could either get the publish process to automatically update the files in `/artifacts` to include the suffix on the image tag, or overwrite `v1.0.0-beta` with the latest each time so the suffix-free tag would work.

**Comment by alok87** [comment]
Thanks for reporting this, I will fix it.

**Comment by alok87** [comment]
@ryantate13 I have pushed the [image](https://hub.docker.com/layers/practodev/workerpodautoscaler/v1.0.0-beta/images/sha256-a8d42f302c039a4cbc6a196176f82114f26a82205bb18876d81b4c8c35680225?context=repo) which was not pushed in dockerhub.

The process of updating the release version in [deployment-template.yaml](https://github.com/practo/k8s-worker-pod-autoscaler/blob/v1.0.0-beta/artifacts/deployment-template.yaml#L31) and [README](https://github.com/practo/k8s-worker-pod-autoscaler/blob/master/README.md) is manual at present. Keeping the issue open till we can make it part of [release.sh](https://github.com/practo/k8s-worker-pod-autoscaler/blob/master/hack/release.sh)
